#pragma once

enum systemCommands {
  SYSTEM_COMMAND_0_SUM,
  SYSTEM_COMMAND_1_PRINT,
  SYSTEM_COMMAND_2_GETKEY,
  SYSTEM_COMMAND_3_PUTCHAR,
  SYSTEM_COMMAND_4_MALLOC,
  SYSTEM_COMMAND_5_FREE,
  SYSTEM_COMMAND_6_PROCESS_LOAD_START
};
void isr80hRegisterCommands();
