FILES= ./build/start.o ./build/os.o ./build/stdlib.o ./build/stdio.o ./build/os.c.o ./build/string.o ./build/memory.o
INCLUDES=
all: ${FILES}
	i686-elf-ld -m elf_i386 -relocatable ${FILES} -o ./stdlib.elf
./build/start.o: ./src/start.asm
	nasm -f elf ./src/start.asm -o ./build/start.o
./build/os.o: ./src/os.asm
	nasm -f elf ./src/os.asm -o ./build/os.o
./build/stdlib.o: ./src/stdlib.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/stdlib.c -o ./build/stdlib.o
./build/string.o: ./src/string.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/string.c -o ./build/string.o
./build/stdio.o: ./src/stdio.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/stdio.c -o ./build/stdio.o
./build/memory.o: ./src/memory.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/memory.c -o ./build/memory.o
./build/os.c.o: ./src/os.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/os.c -o ./build/os.c.o
clean:
	rm -rf ${FILES}
	rm ./blank.elf
	nasm -f elf ./src/start.asm -o ./build/start.o
clean:
	rm -rf ${FILES}
	rm ./stdlib.elf
