FILES= ./build/start.o ./build/os.o ./build/stdlib.o
INCLUDES=
all: ${FILES}
	i686-elf-ld -m elf_i386 -relocatable ${FILES} -o ./stdlib.elf
./build/start.o: ./src/start.asm
	nasm -f elf ./src/start.asm -o ./build/start.o
./build/os.o: ./src/os.asm
	nasm -f elf ./src/os.asm -o ./build/os.o
./build/stdlib.o: ./src/stdlib.c
	i686-elf-gcc ${INCLUDES} $(FLAGS) -std=gnu99 -c ./src/stdlib.c -o ./build/stdlib.o
clean:
	rm -rf ${FILES}
	rm ./blank.elf
	nasm -f elf ./src/start.asm -o ./build/start.o
clean:
	rm -rf ${FILES}
	rm ./stdlib.elf
